### ISSUE TITLE
서버 호스팅 이용시 방이 미국에 생성됩니다.

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#100]
![미국 ;](https://user-images.githubusercontent.com/77501301/105190028-efa98700-5b78-11eb-901d-7f13b8f887d5.PNG)
대충 뒤져보니 위도 경도 맞춰져 있던데 국가코드랑 왜이럴까요

**Comment by dapucita** [comment]
한국에 위치한 서버(제공업체)라고 하더라도, 아이피는 보통 미국 아이피를 가져다가 쓰게 됩니다.

이건 헥스볼이나 봇 때문이 아니라 사실 인터넷의 태생적인 문제이기 때문에
'지역 정보를 덮어쓰는' 편법을 이용해야 합니다.

지역을 변경하는 방법을 설명해놨으니 아래 글을 참고해주세요. ('방의 위치정보 고치기' 항목을 참고하세요)
https://github.com/dapucita/haxbotron/wiki/%5BKorean%5D-%EC%82%AC%EC%A0%84%EC%97%90-%EB%AF%B8%EB%A6%AC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0#%EB%B0%A9%EC%9D%98-%EC%9C%84%EC%B9%98%EC%A0%95%EB%B3%B4-%EA%B3%A0%EC%B9%98%EA%B8%B0-geolocation
