### ISSUE TITLE
승리 패배 시 점수를 조절하고 싶습니다

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#102]
rating 부분 건드리면 되나요?

**Comment by dapucita** [comment]
승/패에 따른 레이팅 가감은 복잡한 계산을 거칩니다.
공식 자체는 https://github.com/dapucita/haxbotron/wiki/HElo-Rating-System 에 공개해놨구요,

공식을 건드는 대신 경기의 **비중**(중요도)을 조정해야합니다.
https://github.com/dapucita/haxbotron/wiki/How-to-change-avatars-by-rating-and-tier
위 문서를 보면 경기의 비중을 의미하는 `K Factor`를 조절하는 부분이 나옵니다.
결론적으로 `K Factor`를 조절하면 레이팅 계산 공식에 의한 레이팅 변동폭인 Δ값을 조정할 수 있습니다.

`resources/HElo/rating.json` 파일을 여신 후에 적절히 수정하시면 됩니다.
```json
"placement_match_chances" : 10, <= 배치고사 횟수입니다.
"factor_k_placement" : 50, <= 배치고사의 중요도입니다.
"factor_k_normal" : 30, <= 일반 경기의 중요도입니다.
"facotr_k_replace" : 10 <= 중도 투입된 경기의 중요도입니다.
```
