### ISSUE TITLE
기존 플레이어 정보 유지한채 업데이트 방법 문의

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#105]
업데이트 올라와서 기존에 있는거에 적용시켜 볼려하는데 db폴더만 붙여넣으면 되나요?
그리고 유저들의 기록은 어떻게 확인할까요 그리고 기존 버젼 투표 다중투표 되는 버그도 생겨서 악용되서 금지시켜놨는데
오류인가요 ?

**Comment by dapucita** [comment]
`db` 폴더를 보시면 `haxbotron.sqlite.db` 가 있습니다.
해당 파일에 모든 플레이어 전적과 밴 이력, 슈퍼어드민 키가 저장됩니다.
업데이트 시 해당 파일을 복붙하시면 기존의 플레이어 데이터가 유지됩니다.
(혹시 모르니 항상 기존의 파일들은 백업해두시길 바랍니다)

현재 플레이어 데이터를 쉽게 확인할 수 있는 웹 기반 관리 시스템을 새로 개발하고 있습니다.
일단 지금은 별도의 프로그램을 사용해 `haxbotron.sqlite.db` 파일을 조회하셔야 합니다.
 `haxbotron.sqlite.db` 파일은 `SQLite`라는 규격을 따릅니다.
[DB Browser for SQLite](https://sqlitebrowser.org/)를 사용하시면 `SQLite` 파일들을 조회/수정할 수 있습니다.

지금 공개한 최신 버전은 `v0.3.5a`입니다. 최신 버전에서는 중복접속 버그가 해결되었습니다.
아마 `v0.3.5`를 사용하고 계실텐데 업데이트 하시길 바랍니다.

중복투표 버그는 이전에 제보는 받았는데 제가 직접 확인한 바가 없습니다.
만약 업데이트 후에도 계속 버그가 발생한다면 꼭 알려주시길 부탁드립니다.

**Comment by gavongra** [comment]
오 .. 그렇군요 커맨드로 킥이나 밴을 할 순 없을까요 ?

**Comment by dapucita** [comment]
채팅창에서 `!super login 키` 로 슈퍼어드민 권한을 얻은 다음
`!super kick #아이디` 혹은 `!super ban #아이디`를 하면 됩니다.

슈퍼어드민 로그인키를 등록하는  방법은
1. GUI런처 상의 메뉴에서 키를 등록하거나
2. 위에서 설명드린 `DB Browser for SQLite`로 DB파일의 `super_admin` 테이블을 수정하시면 됩니다.
