### ISSUE TITLE
게임룰 질문

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#106]
게임룰이 captain, normal, relay 이렇게 세종류가 있는데 제가 보기엔 captain이 적용 되어있는거 같더라구요 이게 어떻게보면 릴레이인데  captain이 활성화되면 어떻게 되는 건가요?  제 의도는 옛날에 주장모드 막 채팅으로 (1 , 2 ) 치면 스펙 목록 순서대로 픽할 수 있었는데 그 규칙인가 싶었습니다 근데 captain 설명보면 그게 맞는거 같은데 이 소스로는 그게 안되는건가요? 
랭크가 존재하는 주장모드도 괜찮은 거 같아서요

**Comment by dapucita** [comment]
(참고: https://github.com/dapucita/haxbotron/wiki/How-to-set-custom-game-rule)

사실 파일 이름은 중요하지 않고 그 안의 설정값만 보시면 됩니다.

어느정도 파악은 하셨겠지만 일부 설정값에 대해 다시 설명을 드리면
```
requisite: {
        minimumPlayers : 본 게임이 시작되기 위한 전체인원(afk 제외)
        eachTeamPlayers : 각 팀의 정원
        timeLimit : 시간제한
        scoreLimit : 점수제한
        teamLock : 팀 이동 제한 여부
    },
autoAdmin: 방장 자동임명 여부
autoOperating: 게임 자동진행 여부
captain: 주장전 모드 여부
statsRecord: 스탯 기록 여부
```
와 같은 역할을 합니다.

말씀하신 `captain` 설정의 경우 예상하신대로 주장전을 위한 설정이 맞지만, 아직 실제로는 지원하지 않고 있습니다.
따라서 `captain` 설정을 켜거나 끄더라도 게임에 영향을 미치지는 않습니다.

미래에 주장전을 지원하기 위해 예비로 만들어둔 옵션이고, 추후에 지원될 예정입니다.

*다음 버전에서는 관리 방식이 웹 기반으로 바뀌고, 설정도 조금씩 바뀔 예정입니다.*
