### ISSUE TITLE
방 두개파는법 문의

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#108]
핫빅으로 따로 파볼려하는데 만약에 컴퓨터로 연다면 다른 컴퓨터로 해야하나요 ?

**Comment by dapucita** [comment]
다음 버전에서 여러 방 운영을 공식적으로 지원할 예정입니다 (지금 계속 개발중입니다)

일단 현재 상황에서는 아래와 같이 하셔야 합니다.
1. `db 서버`는 하나만 켜셔도 됩니다.
2. `core 서버`는 여러개를 켜야 합니다. `core` 폴더를 복사해서 하나 더 여시면 됩니다.
3. 방을 만들때 `RUID`(Room Unique Identifier)를 다르게 설정해야 합니다.
`RUID`는 방의 고유 식별자입니다. `RUID`가 같지 않으면 서로 다른 방으로 취급됩니다.
그런데 지금 `GUI 런처`에서는 `RUID`를 바꿀 수 없습니다. `CLI 런처`를 사용해야 `RUID`를 바꿔서 방을 열 수 있습니다.

지금 버전에서는 다소 번거롭습니다. 다음 버전을 기대해주세요 ㅠㅠ

**Comment by dapucita** [comment]
여러 컴퓨터(서버)에 나눠서 Haxbotron를 켤 수도 있습니다.

컴퓨터가 3대 있고, 아이피가 각각 `10.0.0.1`, `10.0.0.2`, `10.0.0.3` 이라면
`10.0.0.1`에 `db 서버`와 `core 서버`를 켜고,
`10.0.0.2`에는 `core 서버`만 하나 더 켜고,
``10.0.0.3`에도 `core 서버`만 하나 더 켜서
총 1개의 `db 서버`와 3개의 `core 서버`를 운영할 수도 있습니다.
(같은 원리로 `db 서버`를 여러개 켜서 따로 짝지어줄 수도 있습니다)

이 경우 `db  서버`와 `core 서버`의 `.env` 파일을 적절히 설정해주셔야 합니다. 예제는 `.env.sample`을 참고하면 됩니다.

**Comment by dapucita** [comment]
![c](https://user-images.githubusercontent.com/45658904/106582594-8453b200-6587-11eb-8dc2-ffc627e54831.PNG)
새로 개발중인 버전의 작동 예시입니다..

**Comment by gavongra** [comment]
cli를 안쓰고 그냥 코어를 2개해서 하면 그냥 유저정보가 공유된 방이란거죠 ?

**Comment by dapucita** [comment]
네 RUID가 달라야만 다른 방으로 처리됩니다. 같은 RUID를 쓰면  말씀하신 대로 유저 데이터가 공유되기 때문에 바람직한 상황은 아닙니다.

**Comment by gavongra** [comment]
db는 근데 두개키는데 에러뜨던데 cli써야되는거죠 ?

**Comment by dapucita** [comment]
1. 서로 다른 `db 서버가 같은 `포트번호`로 열리면 안됩니다 `.env`를 설정하세요.

2. `db 서버`를 한 컴퓨터에서 두 개 이상 열려면 `core 서버`와 마찬가지로 폴더를 복사해서 새로 열어야 합니다.

**Comment by dapucita** [comment]
v0.4.0 버전 릴리즈했습니다. 해당 버전 사용하시면 여러 방을 간편하게 운영할 수 있습니다
