### ISSUE TITLE
게임 플레이 문제점

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#109]
1. 일단 최근에 투표패치 개인적으로 해주신게 어떤식으로 작용하는지 궁금합니다.
2. 투표 발의인이 퇴장시에 투표 무효화하게 되었으면 좋겠습니다.(이용자 건의사항)
3. 투표 한거 자주 뜨게하게하여 투표 참여유도가 활성화 되었으면 좋겠습니다.(이용자 건의사항)
4. 팀이 백패스한걸(마지막에 찬사람) 몸으로 공끌어서 골대에 넣어서 아군 강퇴시키는 트롤도 있다네요.(이용자 건의사항)
5. 핵스볼이 아무래도 다크한 유저가 있기때문에 완장이 필요하긴 하다고 생각합니다. 제가 하루종일 핵스볼 할 수 도없어서
1300~1400 유저에게 어드민 로그인 코드를 알려줄까라도 생각하다가 최고 레이팅에게 자동으로 어드민이 전승되는 기능도 좋을거 같습니다. (이거는 극한까지 갔을 때 상황)
6.!statsreset 명령어를 잠구는 법도 알려주세요

**Comment by dapucita** [comment]
일단 투표의 기본적인 원리 자체는 이렇습니다:
- 다른 사람에게 투표한 상태로 자기가 나가면, 그 표는 무효화됩니다.
- 다른 사람한테 투표를 했다가, 똑같은 사람에게 다시 투표하면 그 표는 취소됩니다. (!vote #1 한다음에 또 !vote #1하면 취소된다는 뜻입니다)
- 다른 사람에게 투표를 했다가, 또다른 사람에게 투표하면 이전의 표는 취소되고 새로운 사람에게 투표됩니다.
- 자기가 투표를 당한 상태였는데 나갔으면, 그 투표 자체가 무효화됩니다.
- 3명이상 표를 받으면, 그때부터 매 1분마다 `투표 진행 알림`에 이름이 나옵니다.

질문에 대한 답입니다:
1. `다른 사람에게 투표한 상태로 자기가 나가면, 그 표는 무효화됩니다.`에 대한 버그 수정이었습니다

2. 처음 투표한 사람이 나가는 경우 투표를 무효화하는걸 말씀하시는거죠? 해당 건의는 제가 구현한 투표의 컨셉에 맞지 않아 구현하지 않을 예정입니다. 투표 자격에 따로 제한을 두지 않고, 투표를 여는 사람도 따로 구분하지 않기 때문에 불가합니다.

3.  투표 알림이 뜨는 조건과 알림 간격을 조정할 수 있는 옵션을 추후에 추가하도록 하겠습니다.

4.  2년전부터 제기된 문제긴 한데요.. 봇에게 주어지는 유의미한 데이터가 '공을 차는 행위'밖에 없기 때문에 어쩔 수 없습니다. 몸으로 밀고 가는 행위를 인식하려면 공과 모든 사람에 대해 매순간 좌표계산을 해야하기 때문에 프로그램에 부하가 걸립니다. 계속 연구는 해보겠습니다

5. 어드민을 자동으로 부여할 때 자격을 정할 수 있도록 옵션을 추후에 추가하도록 하겠습니다.

6. [이 문서](https://github.com/dapucita/haxbotron/wiki/How-to-disable-some-game-commands)를 참고하시면 됩니다.
`core/resources/command.json` 파일을 열고 `_disabledCommandList` 부분을 수정해주세요.
기본값은 다음과 같습니다:
```
"_disabledCommandList": [
    "sampledisabledcommandname1"
    ,"sampledisabledcommandname2"
],
```

다음과 같이 수정하면 됩니다:
```
"_disabledCommandList": [
    "statsreset"
],
```

**Comment by dapucita** [comment]
혹시 아직도 투표 버그 있으시면 아래 설명대로 `core/controller/commands/vote.ts` 파일을 수정해주세요
1. 29~31번째 줄을 보면 이런 부분이 나옵니다:
```ts
(중략)
if (roomPlayersNumberCheck() >= BotSettings.banVoteAllowMinimum) { // check current players and vote
    window.playerList.get(byPlayer.id)!.voteTarget = targetVoteID; // vote and set
    window.playerList.get(targetVoteID)!.voteGet++; // increase voted count
(중략)
```

2. `if~` 구문 바로 아랫줄에 다음 코드를 추가해주세요:
```ts
    if(window.playerList.has(window.playerList.get(byPlayer.id)!.voteTarget)) {
        window.playerList.get(window.playerList.get(byPlayer.id)!.voteTarget)!.voteGet--;
    }
```

3. 다음과 같이 수정되었으면 다시 빌드하면 됩니다.
```ts
(중략)
if (roomPlayersNumberCheck() >= BotSettings.banVoteAllowMinimum) { // check current players and vote
    if(window.playerList.has(window.playerList.get(byPlayer.id)!.voteTarget)) {
        window.playerList.get(window.playerList.get(byPlayer.id)!.voteTarget)!.voteGet--;
    }
    window.playerList.get(byPlayer.id)!.voteTarget = targetVoteID; // vote and set
    window.playerList.get(targetVoteID)!.voteGet++; // increase voted count
(중략)
```
