### ISSUE TITLE
어드민 임명시의 자격 설정 옵션

### ISSUE THREAD

**Issue by dapucita** [dapucita/haxbotron#110]
어드민을 자동으로 부여할 때 자격을 정할 수 있는 옵션
예) 레이팅 x점 이상 플레이어에게만 어드민을 부여

**Comment by gavongra** [comment]
1.어드민을 잡았을 때 킥만되게하는 거 on off 기능도 있었으면 좋겠습니다 (스크립트 내에서)
2.1300이 잡고있다가 1350가 들어오면 자동으로 넘어가는 기능도 있으면 좋겠습니다

**Comment by dapucita** [comment]
말씀하신 내용도 포함하도록 하겠습니다
의견주셔서 항상 감사드립니다 !!

**Comment by dapucita** [comment]
1번은 `resources/settings.json` 파일의 `antiBanNoPermission` 옵션을 해제하면 어드가 밴도 할 수 있게되는데
 이거 말씀하시는거 아닌가요?

**Comment by gavongra** [comment]
패치된 거 유저데이터 옮기는 방법은 동일한가요 RUID에 따라머 유저데이터 다르다던데

**Comment by dapucita** [comment]
네 db 파일 그대로 갖다쓰시면 됩니다

혹시모르니까 db파일 백업해두시구요

RUID는 안건드신거같은데 기본값 그대로 쓰시면 연동될거에요

**Comment by gavongra** [comment]
configuration schema is unfulfilled. 그 방만드는 페이지에서 create 누르면 이거 뜨네요

**Comment by dapucita** [comment]
문제 파악한 후 알려드리겠습니다

**Comment by dapucita** [comment]
새로 올린 0.4.1로 업뎃해보셔요

그리고 core/out, core/public/out, db/out 이 세 폴더를 지운다음에 다시 빌드해보세요

빌드 시 기존 파일이 안없어지는 경우가 있어서 파일 충돌로 이번과 같은 버그가 발생하는 것 같습니다.

**Comment by dapucita** [comment]
방장 자동 임명시 가장 높은 레이팅을 가진 플레이어를 임명하도록 대체 구현하였음
