### ISSUE TITLE
create 시 onfiguration schema is unfulfilled. 라고 뜹니다

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#113]
토큰 입력외에 해줘야하는게 있나요

**Comment by dapucita** [comment]
자동으로 뜨는 설정값들 따로 옮겨두신다음에

RESET 버튼 눌러서 초기화하고 다시 입력해보셔요

**Comment by dapucita** [comment]
어떤 컴퓨터에서는 되고 어떤 컴퓨터에서는 안돼서 버그 수정중입니다..

**Comment by dapucita** [comment]
새로 올린 0.4.1로 업뎃해보셔요

그리고 `core/out`, `core/public/out`, `db/out` 이 세 폴더를 지운다음에 다시 빌드해보세요

빌드 시 기존 파일이 안없어지는 경우가 있어서 파일 충돌로 이번과 같은 버그가 발생하는 것 같습니다.
