### ISSUE TITLE
유저 데이터 옮기는법 문의

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#118]
기존의 방식과 다른가요 ?

**Comment by dapucita** [comment]
기존에 쓰던 `haxbotron.sqlite.db` 파일을 그대로 사용하시면 됩니다!

그 상태로 서버 켜고 웹 시스템에 접속하시고

 'Room List' 메뉴를 누르시면 기존에 사용했던 RUID들이 뜰거에요

그럼 방을 새로 생성할때 그 RUID를 다시 갖다 쓰면 됩니다.

**Comment by gavongra** [comment]
db 폴더에 옮긴후 빌드하고 해봤는데 아무것도 기록되지 않은 상태인데 어떻게 해야할까요

**Comment by dapucita** [comment]
일부 기능은 아직 준비중이라 저렇게 뜨는거에요

방 생성할때 `RUID`를 `haxbotron-room-default`로 설정하고 만드시면 기존에 사용하던 데이터 연동됩니다
겜 접속해서 확인해보세요

**Comment by gavongra** [comment]
게임 접속해서 확인해봤는데 배치 아바타 계속 떠서 그냥 다푸님이 파놓은거 즐기겠습니다! 귀찮네요

**Comment by dapucita** [comment]
제가 여러 컴퓨터에서 미리 다 테스트해봤거든요

연동이 안되는거는 빈 파일을 옮기셨거나, RUID를 다른걸 입력하셔서 그런거에요

리싸는 지금도 맵이 있기 때문에 바로 운영할 수 있구요, 주장전은 추후에 만들어보도록 하겠습니다. 감사합니다

그리고 테스트방은 다시 닫을거에요 죄송..

**Comment by gavongra** [comment]
근데 저는 RUID목록은 안뜨네요 방을 파고 방을 깨도 RUID 목록에 저장이 안됩니다.
install이나 build 과정에서 war 하나 뜨던거같은데 정상인가요

**Comment by gavongra** [comment]
![core install](https://user-images.githubusercontent.com/77501301/107143999-7c2ab680-697b-11eb-98ea-5126233d05c8.PNG)
core npm install 과정에서 저거 뜨네요

**Comment by gavongra** [comment]
![core run build](https://user-images.githubusercontent.com/77501301/107144047-d297f500-697b-11eb-8d2b-61d98641df9d.PNG)
그후 build

**Comment by dapucita** [comment]
RUID 목록에 뜨려면 플레이어가 한 번 이상 접속한 방이어야 합니다

이전 데이터가 다 날아가신 거라면 아마 db 파일이 비어있는 것 같은데... 파일을 잘못 건드신게 아닌가 싶구요

install 할 때의 warning은 설치되는 패키지에 맥 OS X를 위한 패키지가 들어있어서 그렇습니다. 제가 만든건 아니고 OS X 사용자들 위한 일종의 패치가 포함된거라고 보시면 돼서 별 이상은 없습니다.

build 할 때의 warning은, 빌드되는 파일이 크다는 알림입니다. 웹 관리 시스템의 파일이 큰 건데요, 그래봤자 659KiB정도라 사실 그리 큰 것도 아니고 요즘은 모뎀을 쓰는 시대도 아니라 별로 상관없어요. 결론적으로  실제 작동에는 전혀 이상이 없습니다!

**Comment by gavongra** [comment]
haxbotron.sqlite이 파일은 백업되어 있는데 방을 파고 플레이어 들어와도 RUID 저장되지 않고 머가 문제인지 모르겠네요

**Comment by dapucita** [comment]
haxbotron.sqlite.db 파일도 잘 있고, 방 개설도 잘 된다면 문제는 DB서버 일거같은데요

혹시 DB서버와 연결이 안된거 아닌가요..?

**Comment by gavongra** [comment]
db env 이거 써야하나요 ?

**Comment by dapucita** [comment]
core랑 db를 같은 컴터에서 여실거면 설정안하셔도 됩니다

**Comment by dapucita** [comment]
제가 여러 컴퓨터에서 테스트를 다 해봤거든요.. 지금 안되시는건 뭔가를 빼먹으셔서 안되는거 같아요

1. 사용중인 db 파일이 `haxbotron.sqlite.db`가 맞는지
2. db 서버와 core 서버가 한 컴퓨터에서 실행되는지, 혹은 다른 컴퓨터에서 실행되는지
3. `.env` 파일을 생성했거나, 생성했다면 내용을 어떻게 수정했는지

체크해보셔야 할거같아요

정말 최악의 경우에는 방화벽에 막힌거일수도 있는데
일반적으로는 로컬 아이피에 대해 방화벽이 막지는 않기 때문에 이건 아닐거같아요

**Comment by gavongra** [comment]
4.1?인가 까지는 잘 따라갔다가 웹형태이후 부터 안되는거보면 제 문제라 보기도 어려운거 같습니다

1번은 확인
2번은 둘다 호스팅컴
3번은 미국으로 파지기 때문에 core env true로 바꿔줌
-----------------------------------------------------------------
RUID가 방이 안파진상태에서도 알아서 목록에 뜨는 형식인가요? /
└> 방판후 접속하면 플레이어 목록에 뜬다음 채팅까지해도 목록에 남는게 없습니다
한판이 진행되야 정보가 저장되나요 ? 만들고 접속만할게아니라 ?
└> 위와 같은 이유
아니면 따로 깔아야할 프로그램이 있다던지 ?
└> 저는 node?인가 설명한 것 밖에 깐게 없습니다
실행하면 haxbotron.sqlite.db가 20kb정도의 크기로 생산되고 296kb 짜리 제 백업으로 넣으면 그대로 적용이 안됩니다

**Comment by dapucita** [comment]
![999](https://user-images.githubusercontent.com/45658904/107601667-ba212680-6c6a-11eb-9259-b0dbd3409bdd.PNG)
정상적으로 db가 로드됐으면 Room List에 이런 식으로 사용 이력이 있는 RUID가 뜹니다

일단 본인 컴퓨터에서 연습겸 한 번 해보시구요, 그래도 안되면
제가 데이터가 담긴 db파일을 한 번 봐드리겠습니다
