### ISSUE TITLE
입장시 오류가 뜹니다 

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#126]
![403](https://user-images.githubusercontent.com/77501301/107638349-cdf07b00-6cb2-11eb-9ab7-9bbdeb17e3df.PNG)
데이터가 안불러와지는 이유일까요

**Comment by dapucita** [comment]
IP 허용이 안돼서 DB서버쪽 오류가 뜨는 상황이네요 (Access denied to IP address~)

`.env` 파일에서 `SERVER_WHITELIST_IP` 부분을 이렇게 수정해주세요 :
> SERVER_WHITELIST_IP = "::ffff:127.0.0.1,127.0.0.1"

새로 추가하셔야 할 `::ffff:127.0.0.1`는 `127.0.0.1`(IPv4)를 IPv6 형식으로 표기한 로컬 아이피입니다.
