### ISSUE TITLE
[REQUEST] User based rooms

### ISSUE THREAD

**Issue by madn00b** [dapucita/haxbotron#149]
Hi! 
First off I love the project, but it lacks some features which I believe would be really cool if they were added to the project. 
Since the project already has an authentication process for the web-management, would it be possible to add more users for the master core server, so for example besides the Administrator account, we could create a user and give him the permissions to run the room with some limitations (for ex. number of rooms he can launch, max players etc...)

**Comment by dapucita** [comment]
Thank you for your suggestions. The features you suggested are very nice.

However, I'm busy these days, so I cannot promise an exact schedule.

In fact, Haxbotron provides an API protocol, so anyone can refer to it and implement the desired function if necessary.
