### ISSUE TITLE
1v1, 2v2, 3v3, 4v4, 5v5 etc. game modes

### ISSUE THREAD

**Issue by tanercanbilgin** [dapucita/haxbotron#150]
For example, i want to have maps for when room have 4 people or 6 people or 8. How can i make it?

Also, i want to start record stats when server has 2+ players. Thanks.

**Comment by dapucita** [comment]
Sorry for late answer.

1. You can't load 3+ maps.

2. Recording with conditional options is not supported yet.

Thanks.

**Comment by tanercanbilgin** [comment]
thank you bro
