### ISSUE TITLE
npm run build시 에러가 생깁니다

### ISSUE THREAD

**Issue by gavongra** [dapucita/haxbotron#96]
![asd](https://user-images.githubusercontent.com/77501301/104806569-e6888500-581b-11eb-8d36-19a2eed8733c.PNG)
어떻게 해야할까요

**Comment by gavongra** [comment]
1대1 봇방은 정상적으로 만들어지는걸 확인했습니다 이건 안되네요

**Comment by dapucita** [comment]
아직 문서를 업데이트하지 않아서 그렇습니다 ([최신 문서](https://github.com/dapucita/haxbotron/wiki/Getting-Started)는 아직 작성중입니다)

최신 버전은 core와 db 서버 두개로 분리해놨는데요,

core 폴더로 가셔서 빌드하시고, db 폴더에서도 또 한 번 빌드하셔야 합니다.

이후에 db서버를 켜고, 그 다음으로 core 서버를 실행하시면 됩니다.

불편을 드려 죄송합니다.

**Comment by gavongra** [comment]
먼저 core을 빌드하고 db폴더가서 빌드하고 db 실행시키니 cmd에 더 이상 입력이 안돼서 하나 더 켜서 core 실행시켜줬는데
런쳐는 뜨는데 public 체크한 상태에서도 목록에 방이 안뜨네요

2021년 1월 18일 (월) 오후 4:36, dapucita <notifications@github.com>님이 작성:

**Comment by dapucita** [comment]
확인 결과 버그가 있었습니다.
수정하였으니 버전 0.3.5 릴리즈를 다시 받아서 시도해주세요

제보 감사드립니다
